CREATE TABLE Evento(
   ID_Evento  INTEGER  NOT NULL PRIMARY KEY 
  ,Esporte    VARCHAR(17) NOT NULL
  ,Disciplina VARCHAR(21) NOT NULL
  ,Nome       VARCHAR(35) NOT NULL
  ,Sexo       VARCHAR(6) NOT NULL
  ,Local      VARCHAR(112) NOT NULL
  ,CONSTRAINT fk_esporte_evento FOREIGN KEY (Esporte) REFERENCES Esporte(Nome)
);
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (701492,'aquatics','backstroke','Women''s 100m Backstroke','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (305278,'aquatics','backstroke','Women''s 200m Backstroke','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (708010,'aquatics','backstroke','Men''s 100m Backstroke','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (729643,'aquatics','backstroke','Men''s 200m Backstroke','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (567019,'aquatics','breaststroke','Women''s 100m Breaststroke','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (607924,'aquatics','breaststroke','Women''s 200m Breaststroke','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (519818,'aquatics','breaststroke','Men''s 100m Breaststroke','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (778941,'aquatics','breaststroke','Men''s 200m Breaststroke','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (795006,'aquatics','butterfly','Women''s 100m Butterfly','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (93436,'aquatics','butterfly','Women''s 200m Butterfly','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (649324,'aquatics','butterfly','Men''s 100m Butterfly','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (943021,'aquatics','butterfly','Men''s 200m Butterfly','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (772359,'aquatics','diving','Women''s 10m Platform','female','Maria Lenk Aquatics Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (228171,'aquatics','diving','Women''s 3m Springboard','female','Maria Lenk Aquatics Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (305987,'aquatics','diving','Women''s Synchronised 10m Platform','female','Maria Lenk Aquatics Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (745896,'aquatics','diving','Women''s Synchronised 3m Springboard','female','Maria Lenk Aquatics Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (574103,'aquatics','diving','Men''s 10m Platform','male','Maria Lenk Aquatics Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (48684,'aquatics','diving','Men''s 3m Springboard','male','Maria Lenk Aquatics Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (524580,'aquatics','diving','Men''s Synchronised 10m Platform','male','Maria Lenk Aquatics Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (694510,'aquatics','diving','Men''s Synchronised 3m Springboard','male','Maria Lenk Aquatics Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (760140,'aquatics','freestyle','Women''s 100m Freestyle','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (872869,'aquatics','freestyle','Women''s 200m Freestyle','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (789774,'aquatics','freestyle','Women''s 4 x 100m Freestyle Relay','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (391049,'aquatics','freestyle','Women''s 4 x 200m Freestyle Relay','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (568906,'aquatics','freestyle','Women''s 400m Freestyle','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (229032,'aquatics','freestyle','Women''s 50m Freestyle','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (121264,'aquatics','freestyle','Women''s 800m Freestyle','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (82103,'aquatics','freestyle','Men''s 100m Freestyle','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (338784,'aquatics','freestyle','Men''s 1500m Freestyle','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (646337,'aquatics','freestyle','Men''s 200m Freestyle','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (593058,'aquatics','freestyle','Men''s 4 x 100m Freestyle Relay','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (19516,'aquatics','freestyle','Men''s 4 x 200m Freestyle Relay','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (160248,'aquatics','freestyle','Men''s 400m Freestyle','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (747079,'aquatics','freestyle','Men''s 50m Freestyle','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (327702,'aquatics','marathon swimming','Women''s 10km','female','Fort Copacabana');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (424553,'aquatics','marathon swimming','Men''s 10km','male','Fort Copacabana');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (484043,'aquatics','medley','Women''s 200m Individual Medley','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (370610,'aquatics','medley','Women''s 4 x 100m Medley Relay','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (339538,'aquatics','medley','Women''s 400m Individual Medley','female','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (918604,'aquatics','medley','Men''s 200m Individual Medley','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (352612,'aquatics','medley','Men''s 4 x 100m Medley Relay','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (482176,'aquatics','medley','Men''s 400m Individual Medley','male','Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (492931,'aquatics','synchronised swimming','Duets','female','Maria Lenk Aquatics Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (746451,'aquatics','synchronised swimming','Teams','female','Maria Lenk Aquatics Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (183313,'aquatics','water polo','Women','female','Maria Lenk Aquatics Centre, Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (278940,'aquatics','water polo','Men','male','Maria Lenk Aquatics Centre, Olympic Aquatics Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (177885,'archery','archery','Women''s Individual','female','Sambodromo');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (590313,'archery','archery','Women''s Team','female','Sambodromo');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (898524,'archery','archery','Men''s Individual','male','Sambodromo');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (1120,'archery','archery','Men''s Team','male','Sambodromo');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (272651,'athletics','combined','Women''s Heptathlon','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (772822,'athletics','combined','Men''s Decathlon','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (628221,'athletics','jumps','Women''s High Jump','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (757567,'athletics','jumps','Women''s Long Jump','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (647207,'athletics','jumps','Women''s Pole Vault','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (324700,'athletics','jumps','Women''s Triple Jump','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (236418,'athletics','jumps','Men''s High Jump','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (770978,'athletics','jumps','Men''s Long Jump','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (323149,'athletics','jumps','Men''s Pole Vault','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (606367,'athletics','jumps','Men''s Triple Jump','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (256986,'athletics','road','Women''s 20km Walk','female','Pontal');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (124738,'athletics','road','Women''s Marathon','female','Sambodromo');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (449001,'athletics','road','Men''s 20km Walk','male','Pontal');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (296930,'athletics','road','Men''s 50km Walk','male','Pontal');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (91115,'athletics','road','Men''s Marathon','male','Sambodromo');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (551739,'athletics','throws','Women''s Discus Throw','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (757855,'athletics','throws','Women''s Hammer Throw','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (153195,'athletics','throws','Women''s Javelin Throw','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (341126,'athletics','throws','Women''s Shot Put','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (249009,'athletics','throws','Men''s Discus Throw','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (571592,'athletics','throws','Men''s Hammer Throw','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (919516,'athletics','throws','Men''s Javelin Throw','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (777467,'athletics','throws','Men''s Shot Put','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (532996,'athletics','track','Women''s 10,000m','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (598702,'athletics','track','Women''s 100m','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (971198,'athletics','track','Women''s 100m Hurdles','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (222827,'athletics','track','Women''s 1500m','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (261741,'athletics','track','Women''s 200m','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (561270,'athletics','track','Women''s 3000m Steeplechase','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (879766,'athletics','track','Women''s 4 x 100m Relay','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (927436,'athletics','track','Women''s 4 x 400m Relay','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (539936,'athletics','track','Women''s 400m','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (1075,'athletics','track','Women''s 400m Hurdles','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (802434,'athletics','track','Women''s 5000m','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (347244,'athletics','track','Women''s 800m','female','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (752,'athletics','track','Men''s 10,000m','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (423428,'athletics','track','Men''s 100m','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (745937,'athletics','track','Men''s 110m Hurdles','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (43204,'athletics','track','Men''s 1500m','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (226698,'athletics','track','Men''s 200m','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (715173,'athletics','track','Men''s 3000m Steeplechase','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (778161,'athletics','track','Men''s 4 x 100m Relay','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (625766,'athletics','track','Men''s 4 x 400m Relay','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (277121,'athletics','track','Men''s 400m','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (747066,'athletics','track','Men''s 400m Hurdles','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (530376,'athletics','track','Men''s 5000m','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (698080,'athletics','track','Men''s 800m','male','Olympic Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (52854,'badminton','badminton','Women''s Doubles','female','Riocentro - Pavilion 4');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (159174,'badminton','badminton','Women''s Singles','female','Riocentro - Pavilion 4');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (84421,'badminton','badminton','Men''s Doubles','male','Riocentro - Pavilion 4');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (840593,'badminton','badminton','Men''s Singles','male','Riocentro - Pavilion 4');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (206559,'badminton','badminton','Mixed Doubles','mixed','Riocentro - Pavilion 4');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (272277,'basketball','basketball','Women','female','Carioca Arena 1, Youth Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (81838,'basketball','basketball','Men','male','Carioca Arena 1');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (484495,'boxing','boxing','Women''s Fly (48-51kg)','female','Riocentro - Pavilion 6');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (806904,'boxing','boxing','Women''s Light (57-60kg)','female','Riocentro - Pavilion 6');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (57360,'boxing','boxing','Women''s Middle (69-75kg)','female','Riocentro - Pavilion 6');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (687735,'boxing','boxing','Men''s Bantam (56kg)','male','Riocentro - Pavilion 6');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (649755,'boxing','boxing','Men''s Fly (52kg)','male','Riocentro - Pavilion 6');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (724817,'boxing','boxing','Men''s Heavy (91kg)','male','Riocentro - Pavilion 6');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (108063,'boxing','boxing','Men''s Light (60kg)','male','Riocentro - Pavilion 6');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (770242,'boxing','boxing','Men''s Light Fly (46-49kg)','male','Riocentro - Pavilion 6');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (762470,'boxing','boxing','Men''s Light Heavy (81kg)','male','Riocentro - Pavilion 6');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (2486,'boxing','boxing','Men''s Light Welter (64kg)','male','Riocentro - Pavilion 6');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (980841,'boxing','boxing','Men''s Middle (75kg)','male','Riocentro - Pavilion 6');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (310726,'boxing','boxing','Men''s Super Heavy (+91kg)','male','Riocentro - Pavilion 6');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (129664,'boxing','boxing','Men''s Welter (69kg)','male','Riocentro - Pavilion 6');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (673367,'canoe','canoe slalom','Kayak (K1) Women','female','Whitewater Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (750078,'canoe','canoe slalom','Canoe Double (C2) Men','male','Whitewater Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (804809,'canoe','canoe slalom','Canoe Single (C1) Men','male','Whitewater Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (791569,'canoe','canoe slalom','Kayak (K1) Men','male','Whitewater Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (413708,'canoe','canoe sprint','Women''s Kayak Double 500m','female','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (628511,'canoe','canoe sprint','Women''s Kayak Four 500m','female','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (675323,'canoe','canoe sprint','Women''s Kayak Single 200m','female','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (414210,'canoe','canoe sprint','Women''s Kayak Single 500m','female','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (617,'canoe','canoe sprint','Men''s Canoe Double 1000m','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (705596,'canoe','canoe sprint','Men''s Canoe Single 1000m','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (74948,'canoe','canoe sprint','Men''s Canoe Single 200m','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (130176,'canoe','canoe sprint','Men''s Kayak Double 1000m','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (225144,'canoe','canoe sprint','Men''s Kayak Double 200m','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (295266,'canoe','canoe sprint','Men''s Kayak Four 1000m','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (285067,'canoe','canoe sprint','Men''s Kayak Single 1000m','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (140333,'canoe','canoe sprint','Men''s Kayak Single 200m','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (939257,'cycling','cycling bmx','Women','female','Olympic BMX Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (411469,'cycling','cycling bmx','Men','male','Olympic BMX Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (609527,'cycling','cycling mountain bike','Women''s Cross-country','female','Mountain Bike Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (397729,'cycling','cycling mountain bike','Men''s Cross-country','male','Mountain Bike Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (246370,'cycling','cycling road','Women''s Individual Time Trial','female','Pontal');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (302623,'cycling','cycling road','Women''s Road Race','female','Fort Copacabana');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (513271,'cycling','cycling road','Men''s Individual Time Trial','male','Pontal');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (69639,'cycling','cycling road','Men''s Road Race','male','Fort Copacabana');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (86410,'cycling','cycling track','Women''s Keirin','female','Rio Olympic Velodrome');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (553518,'cycling','cycling track','Women''s Omnium','female','Rio Olympic Velodrome');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (773540,'cycling','cycling track','Women''s Sprint','female','Rio Olympic Velodrome');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (674617,'cycling','cycling track','Women''s Team Pursuit','female','Rio Olympic Velodrome');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (593019,'cycling','cycling track','Women''s Team Sprint','female','Rio Olympic Velodrome');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (880547,'cycling','cycling track','Men''s Keirin','male','Rio Olympic Velodrome');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (41008,'cycling','cycling track','Men''s Omnium','male','Rio Olympic Velodrome');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (718759,'cycling','cycling track','Men''s Sprint','male','Rio Olympic Velodrome');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (492594,'cycling','cycling track','Men''s Team Pursuit','male','Rio Olympic Velodrome');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (623046,'cycling','cycling track','Men''s Team Sprint','male','Rio Olympic Velodrome');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (195034,'equestrian','dressage','Dressage Individual','mixed','Olympic Equestrian Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (278761,'equestrian','dressage','Dressage Team','mixed','Olympic Equestrian Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (462390,'equestrian','eventing','Eventing Individual','mixed','Olympic Equestrian Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (692313,'equestrian','eventing','Eventing Team','mixed','Olympic Equestrian Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (770871,'equestrian','jumping','Jumping Individual','mixed','Olympic Equestrian Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (371159,'equestrian','jumping','Jumping Team','mixed','Olympic Equestrian Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (354957,'fencing','individual','Women''s Foil Individual','female','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (733035,'fencing','individual','Women''s Sabre Individual','female','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (521073,'fencing','individual','Women''s ��p̩e Individual','female','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (333035,'fencing','individual','Men''s Foil Individual','male','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (581647,'fencing','individual','Men''s Sabre Individual','male','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (160239,'fencing','individual','Men''s ��p̩e Individual','male','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (978073,'fencing','team','Women''s Sabre Team','female','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (497812,'fencing','team','Women''s ��p̩e Team','female','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (399773,'fencing','team','Men''s Foil Team','male','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (100515,'fencing','team','Men''s ��p̩e Team','male','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (784723,'football','football','Women','female','Mineiṛo, Olympic Stadium, Fonte Nova Arena, Amazonia Arena, Corinthians Arena, Mane Garrincha Stadium, Maracana');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (575557,'football','football','Men','male','Mineiṛo, Olympic Stadium, Fonte Nova Arena, Amazonia Arena, Corinthians Arena, Mane Garrincha Stadium, Maracana');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (272378,'golf','golf','Women''s Individual Stroke Play','female','Olympic Golf Course');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (709824,'golf','golf','Men''s Individual Stroke Play','male','Olympic Golf Course');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (148864,'gymnastics','artistic gymnastics','Women''s Balance Beam','female','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (816897,'gymnastics','artistic gymnastics','Women''s Floor Exercise','female','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (884887,'gymnastics','artistic gymnastics','Women''s Individual All-Around','female','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (866079,'gymnastics','artistic gymnastics','Women''s Team','female','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (259226,'gymnastics','artistic gymnastics','Women''s Uneven Bars','female','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (14799,'gymnastics','artistic gymnastics','Women''s Vault','female','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (762301,'gymnastics','artistic gymnastics','Men''s Floor Exercise','male','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (716295,'gymnastics','artistic gymnastics','Men''s Horizontal Bar','male','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (818747,'gymnastics','artistic gymnastics','Men''s Individual All-Around','male','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (120863,'gymnastics','artistic gymnastics','Men''s Parallel Bars','male','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (68030,'gymnastics','artistic gymnastics','Men''s Pommel Horse','male','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (856285,'gymnastics','artistic gymnastics','Men''s Rings','male','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (823595,'gymnastics','artistic gymnastics','Men''s Team','male','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (876371,'gymnastics','artistic gymnastics','Men''s Vault','male','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (770887,'gymnastics','rhythmic gymnastics','Group All-Around','female','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (981370,'gymnastics','rhythmic gymnastics','Individual All-Around','female','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (588395,'gymnastics','trampoline gymnastics','Women','female','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (673301,'gymnastics','trampoline gymnastics','Men','male','Rio Olympic Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (924904,'handball','handball','Women','female','Future Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (725677,'handball','handball','Men','male','Future Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (975106,'hockey','hockey','Women','female','Olympic Hockey Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (181638,'hockey','hockey','Men','male','Olympic Hockey Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (620336,'judo','judo','Women +78 kg','female','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (83320,'judo','judo','Women -48 kg','female','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (96282,'judo','judo','Women -52 kg','female','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (906988,'judo','judo','Women -57 kg','female','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (484944,'judo','judo','Women -63 kg','female','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (126828,'judo','judo','Women -70 kg','female','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (926497,'judo','judo','Women -78 kg','female','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (54510,'judo','judo','Men +100 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (547152,'judo','judo','Men -100 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (54156,'judo','judo','Men -60 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (456055,'judo','judo','Men -66 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (138897,'judo','judo','Men -73 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (489867,'judo','judo','Men -81 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (498135,'judo','judo','Men -90 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (889276,'modern pentathlon','modern pentathlon','Women''s Individual','female','Deodoro Aquatics Centre, Deodoro Stadium, Youth Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (894957,'modern pentathlon','modern pentathlon','Men''s Individual','male','Deodoro Aquatics Centre, Deodoro Stadium, Youth Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (14589,'rowing','rowing','Lightweight Women''s Double Sculls','female','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (906628,'rowing','rowing','Women''s Double Sculls','female','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (572390,'rowing','rowing','Women''s Eight','female','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (44739,'rowing','rowing','Women''s Pair','female','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (86126,'rowing','rowing','Women''s Quadruple Sculls','female','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (902619,'rowing','rowing','Women''s Single Sculls','female','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (928605,'rowing','rowing','Lightweight Men''s Double Sculls','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (283950,'rowing','rowing','Lightweight Men''s Four','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (952064,'rowing','rowing','Men''s Double Sculls','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (825674,'rowing','rowing','Men''s Eight','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (103563,'rowing','rowing','Men''s Four','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (196444,'rowing','rowing','Men''s Pair','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (897153,'rowing','rowing','Men''s Quadruple Sculls','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (254777,'rowing','rowing','Men''s Single Sculls','male','Lagoa Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (175098,'rugby sevens','rugby sevens','Women','female','Deodoro Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (767382,'rugby sevens','rugby sevens','Men','male','Deodoro Stadium');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (11625,'sailing','sailing','470 Women','female','Marina da Gloria');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (684310,'sailing','sailing','49er FX Women','female','Marina da Gloria');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (410849,'sailing','sailing','Laser Radial Women','female','Marina da Gloria');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (526496,'sailing','sailing','RS:X Women','female','Marina da Gloria');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (9629,'sailing','sailing','470 Men','male','Marina da Gloria');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (66645,'sailing','sailing','49er Men','male','Marina da Gloria');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (161800,'sailing','sailing','Finn Men','male','Marina da Gloria');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (100052,'sailing','sailing','Laser Men','male','Marina da Gloria');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (980413,'sailing','sailing','RS:X Men','male','Marina da Gloria');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (406751,'sailing','sailing','Nacra 17 Mixed','mixed','Marina da Gloria');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (758084,'shooting','shooting','10m Air Pistol Women','female','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (835974,'shooting','shooting','10m Air Rifle Women','female','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (421231,'shooting','shooting','25m Pistol Women','female','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (292350,'shooting','shooting','50m Rifle 3 Positions Women','female','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (455900,'shooting','shooting','Skeet Women','female','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (199816,'shooting','shooting','Trap Women','female','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (892005,'shooting','shooting','10m Air Pistol Men','male','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (758755,'shooting','shooting','10m Air Rifle Men','male','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (249014,'shooting','shooting','25m Rapid Fire Pistol Men','male','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (306711,'shooting','shooting','50m Pistol Men','male','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (330799,'shooting','shooting','50m Rifle 3 Positions Men','male','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (683918,'shooting','shooting','50m Rifle Prone Men','male','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (231643,'shooting','shooting','Double Trap Men','male','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (460505,'shooting','shooting','Skeet Men','male','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (11098,'shooting','shooting','Trap Men','male','Olympic Shooting Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (760387,'table tennis','table tennis','Women''s Singles','female','Riocentro - Pavilion 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (619998,'table tennis','table tennis','Women''s Team','female','Riocentro - Pavilion 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (382356,'table tennis','table tennis','Men''s Singles','male','Riocentro - Pavilion 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (298763,'table tennis','table tennis','Men''s Team','male','Riocentro - Pavilion 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (204037,'taekwondo','taekwondo','Women +67kg','female','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (507765,'taekwondo','taekwondo','Women -49kg','female','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (388926,'taekwondo','taekwondo','Women -57kg','female','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (747102,'taekwondo','taekwondo','Women -67kg','female','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (734361,'taekwondo','taekwondo','Men +80kg','male','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (819891,'taekwondo','taekwondo','Men -58kg','male','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (241742,'taekwondo','taekwondo','Men -68kg','male','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (661229,'taekwondo','taekwondo','Men -80kg','male','Carioca Arena 3');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (619169,'tennis','tennis','Women''s Doubles','female','Olympic Tennis Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (302510,'tennis','tennis','Women''s Singles','female','Olympic Tennis Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (766150,'tennis','tennis','Men''s Doubles','male','Olympic Tennis Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (973448,'tennis','tennis','Men''s Singles','male','Olympic Tennis Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (376905,'tennis','tennis','Mixed Doubles','mixed','Olympic Tennis Centre');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (586550,'triathlon','triathlon','Women','female','Fort Copacabana');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (705045,'triathlon','triathlon','Men','male','Fort Copacabana');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (558386,'volleyball','beach volleyball','Women','female','Beach Volleyball Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (245983,'volleyball','beach volleyball','Men','male','Beach Volleyball Arena');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (894809,'volleyball','volleyball','Women','female','Maracanazinho');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (976855,'volleyball','volleyball','Men','male','Maracanazinho');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (61753,'weightlifting','weightlifting','Women''s +75kg','female','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (875734,'weightlifting','weightlifting','Women''s 48kg','female','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (54259,'weightlifting','weightlifting','Women''s 53kg','female','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (797257,'weightlifting','weightlifting','Women''s 58kg','female','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (512287,'weightlifting','weightlifting','Women''s 63kg','female','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (677718,'weightlifting','weightlifting','Women''s 69kg','female','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (417256,'weightlifting','weightlifting','Women''s 75kg','female','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (212799,'weightlifting','weightlifting','Men''s +105kg','male','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (902263,'weightlifting','weightlifting','Men''s 105kg','male','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (182568,'weightlifting','weightlifting','Men''s 56kg','male','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (273149,'weightlifting','weightlifting','Men''s 62kg','male','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (883392,'weightlifting','weightlifting','Men''s 69kg','male','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (82845,'weightlifting','weightlifting','Men''s 77kg','male','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (415046,'weightlifting','weightlifting','Men''s 85kg','male','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (747577,'weightlifting','weightlifting','Men''s 94kg','male','Riocentro - Pavilion 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (400419,'wrestling','freestyle','Women''s Freestyle 48 kg','female','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (212163,'wrestling','freestyle','Women''s Freestyle 53 kg','female','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (504233,'wrestling','freestyle','Women''s Freestyle 58 kg','female','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (848007,'wrestling','freestyle','Women''s Freestyle 63 kg','female','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (418998,'wrestling','freestyle','Women''s Freestyle 69 kg','female','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (588362,'wrestling','freestyle','Women''s Freestyle 75 kg','female','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (808414,'wrestling','freestyle','Men''s Freestyle 125 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (834744,'wrestling','freestyle','Men''s Freestyle 57 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (633484,'wrestling','freestyle','Men''s Freestyle 65 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (525167,'wrestling','freestyle','Men''s Freestyle 74 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (524420,'wrestling','freestyle','Men''s Freestyle 86 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (716856,'wrestling','freestyle','Men''s Freestyle 97 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (128413,'wrestling','greco roman','Men''s Greco-Roman 130 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (755045,'wrestling','greco roman','Men''s Greco-Roman 59 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (331407,'wrestling','greco roman','Men''s Greco-Roman 66 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (169856,'wrestling','greco roman','Men''s Greco-Roman 75 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (858736,'wrestling','greco roman','Men''s Greco-Roman 85 kg','male','Carioca Arena 2');
INSERT INTO Evento(ID_Evento,Esporte,Disciplina,Nome,Sexo,Local) VALUES (767420,'wrestling','greco roman','Men''s Greco-Roman 98 kg','male','Carioca Arena 2');
